remove windows 2004 sac, bump versions
rancher/fluentd pull request #52
Opened 2021-11-09 20:07 UTC by rosskirkpat

- remove Windows Server 2004 SAC from drone build steps and manifest template
- fix a few aliases in package.ps1 to use full cmdlet
- bump to dapper 0.5.7
- bump to go1.16.9 in Dockerfile.dapper (this may introduce build issues as we are jumping from go1.9 to 1.16)

2021-11-09 20:53 UTC, nickgerace submitted a review, later dismissed

2021-11-10 16:46 UTC, nickgerace approved these changes
LGTM! Great changes all around Ross. Let's squash commits if/once @paynejacob approces

2021-11-10 17:41 UTC, paynejacob requested changes
squash commits, other than that looks good.

2021-11-10 17:45 UTC, rosskirkpat commented
Commits squashed

2021-11-10 17:47 UTC, paynejacob approved these changes

2021-11-10 18:51 UTC, merged